domain: sandman-ba.github.io
url: https://sandman-ba.github.io
baseurl: /bameneyro/

include: ['_pages']

defaults:
  -
    scope:
      path: "/assets/"
    values:
      permalink: /:path
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Bernardo Ameneyro"
      keywords: "Ameneyro, Bernardo, Quantum Computing, Topological Data Analysis, Machine Learning, Mathematics, LaTeX, Python, Large Language Models"
